sudo: required
services: docker

env:
  global:
    - DEBUG=true
    - secure: "KUFZxAXEg5LmqyzgriYx2S+4OZHUJb9JkLdG0vOjrhrj1e/zzuptU0cz8SQGH002bS4Wwxl2KHjwAlkP2CE0EuGuGsqVLasHb11O43RF8+0xYQSE0WlED7WtoCkpSvIYuvsewU9LQVQMu7vnc4YG8rMerhc0MXNqF2DFT5eZ+uKNDx8CpeuLTRSOn3jRE+Xp1Kdn9ouCst4ppQqkQz5a0/esNKGl3a5EF2Sf6+b/0L5jOplz3+Ts8VvUAWjkPBCem+AVbYoJGOv9r5/8AEFTnDcbIoxYEHGPPsrwrA6WIA2w+mKvL1CbiCRZxJLu0zSkZEAv9lXnWN6nN6p32Codw9Kfq5e1TJ349LEMi0TrpeQWJBJVZYddJI25K6EP3PExSINYFBOA67TEnAiYNDHjm/92ZfxKdM/6oKCu/UzrwATwPH8Zs2FloPVGGEA6gHEf1RwMcyHCOvDYPzFTldoi7DL54jfa0ros1Yrqv7W/yC3LE+4P0TlfakEveesOgd3XiEAqengx16H9ln+TQHw+ubok2RRSp9AOOocEQ5JYpEq7RYtv458GVnf7fN11G9QSHN4Uv7VHXIbQOyqH831c55sKkhCc9OksKaOGQgHMXm94YaO9BCeMzmX/BCV3LyC9IBviFwQRGg51aXfXz5BOHpM6NWsY9skNpeWDHg3jI4I="
    - secure: "5jOjaE9OOOrZ2mrvKPYcXFQmowtpaP+r5eD4bR+DAz1462guXNXbcWd1qBgLOiSHTpW9eb+l0zNMmsIADDAcsm7FwSO9xnaCk7tp9mtIy6YWrRbQwTB82juh26MJFvX/VkBsdvCd9WM8a3e0I/Hy4cA14J7SGaI07kPQTO7Kd+HUQe79g89pOqmtTiAKx9Hm9eOwnO66Hgufl7vaXfiOEJttX5olyVLLw2kWyJYQo51GNq/44nzHBaRABKTnbX9ktcYaRnAJHPk72O/nJ/a/t2ftI9kQCoqvpx+yJLbFoKh+HTQToMLJRz2hxyXpBW6SCLA6w/ub9ZZ6jw04a2g2xM8p7LWRKSqfK5KtV0mDKLz0QQLI77dabbRIfYuKdLOamqIXVi1HJVOWKp9xg8KYPevg69MbFSbYE4fPT5gxxai1kW2MX9IhX8aW8owKPixfH5RBCGXSy6kKieCF5nX7fcStmWN3kdptS3CmyqFxi0nFr5k7j5J0LQ3kHOUi6OQDGGWJe9AoX1nZDeEjuLGYfQ73DN56XX7JHylqV39gvzwUAk09XOnmQgX3b5JFEeZDi28oG+oHuMwQg2C0LDVfA+hV14pW6Cp4KkXhF8qhkpZSh/jKHPK6UGKS2UQ3brg/YRQLXhk2O9Bsz+hNqzCy/rALQ8/E1kHwxkFYQWxHRyo="

script:
  # Build image
  - make build

  # run image
  - make start && sleep 30

  # Test image
  - make test

after_script:
  - docker images

# To have `DOCKER_USER` and `DOCKER_PASSWORD`
# use `travis env set DOCKER_USER ...`
# use `travis env set DOCKER_PASSWORD ...`
before_script:
  - make login

deploy:
  provider: script
  script: make push
  on:
    branch: master
