sudo: required
services: docker

env:
  global:
    - DEBUG=true

script:
  # Build image
  - make build

  # run image
  - make start && sleep 30

  # Test image
  - make test

after_script:
  - docker images

# To have `DOCKER_USER` and `DOCKER_PASSWORD`
# use `travis env set DOCKER_USER ...`
# use `travis env set DOCKER_PASSWORD ...`
before_deploy:
  - make login

deploy:
  provider: script
  script: make push
  on:
    branch: master
